### ISSUE TITLE
Failed to activate the language-ansi-styles package & Uncaught TypeError: state.registry.startIdForScope is not a function

### ISSUE THREAD

**Issue by mc21301** [lloiser/language-ansi-styles#3]
[Enter steps to reproduce:] Double-clicking on *.txt file containing ANSI color escape sequences throws the below errors.

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [language-ansi-styles](https://github.com/lloiser/language-ansi-styles) package 0.0.2

### Stack Trace

Failed to activate the language-ansi-styles package

```
At this.registry.startIdForScope is not a function

TypeError: this.registry.startIdForScope is not a function
    at AnsiStylesGrammar.startIdForScope (/packages/language-ansi-styles/lib/ansi-styles-grammar.js:28:26)
    at TextMateLanguageMode.tokenizedLineForRow (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-mate-language-mode.js:428:30)
    at TagFinder.module.exports.TagFinder.scopesForPositionMatchRegex (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:53:36)
    at TagFinder.module.exports.TagFinder.isCursorOnTag (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:45:25)
    at TagFinder.module.exports.TagFinder.findMatchingTags (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:207:22)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:126:41)
    at ~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:3:65
    at buffer.onDidChangeLanguageMode (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor.js:741:13)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.setLanguageMode (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:1373:28)
    at grammarScoresByBuffer.forEach (~/AppData/Local/atom/app-1.24.0/resources/app/src/grammar-registry.js:300:22)
    at Map.forEach (native)
    at GrammarRegistry.grammarAddedOrUpdated (~/AppData/Local/atom/app-1.24.0/resources/app/src/grammar-registry.js:287:38)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at GrammarRegistry.module.exports.GrammarRegistry.addGrammar (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/first-mate/lib/grammar-registry.js:80:26)
    at GrammarRegistry.addGrammar (~/AppData/Local/atom/app-1.24.0/resources/app/src/grammar-registry.js:355:40)
    at Object.activate (/packages/language-ansi-styles/lib/main.js:12:21)
    at Package.activateNow (~/AppData/Local/atom/app-1.24.0/resources/app/src/package.js:230:33)
    at measure (~/AppData/Local/atom/app-1.24.0/resources/app/src/package.js:206:33)
    at Package.measure (~/AppData/Local/atom/app-1.24.0/resources/app/src/package.js:88:25)
    at activationPromise.Promise (~/AppData/Local/atom/app-1.24.0/resources/app/src/package.js:200:20)
    at Package.activate (~/AppData/Local/atom/app-1.24.0/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.24.0/resources/app/src/package-manager.js:695:42)
    at ~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (~/AppData/Local/atom/app-1.24.0/resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.24.0/resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -0:21.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
comment 0.6.1 
copy-path 0.4.2 
cucumber 0.6.0 
cucumber-autocomplete 0.7.2 
cucumber-step 0.2.0 
directory-color 0.3.0 
export-html 3.1.0 
git-plus 7.10.0 
language-ansi-styles 0.0.2 
language-cucumber 0.0.1 
language-groovy 0.7.0 
language-jenkinsfile 0.1.1 
language-terraform 0.8.1 
markdown-preview-plus 2.5.1 
open-bash-git 2.3.3 
platformio-ide-terminal 2.8.0 
print-atom 0.1.1 
print-code 0.7.1 
remote-ftp 2.1.4 
ruby-test 1.0.2 
split-diff 1.5.2 
terraform-fmt 0.3.0 
vim-mode-plus 1.28.0 
```

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [language-ansi-styles](https://github.com/lloiser/language-ansi-styles) package 0.0.2

### Stack Trace

Uncaught TypeError: state.registry.startIdForScope is not a function

```
At C:\Users\mc21301\.atom\packages\language-ansi-styles\lib\convert.js:303

TypeError: state.registry.startIdForScope is not a function
    at open (/packages/language-ansi-styles/lib/convert.js:303:30)
    at convert (/packages/language-ansi-styles/lib/convert.js:15:5)
    at AnsiStylesGrammar.tokenizeLine (/packages/language-ansi-styles/lib/ansi-styles-grammar.js:49:12)
    at TextMateLanguageMode.buildTokenizedLineForRowWithText (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-mate-language-mode.js:407:50)
    at TextMateLanguageMode.buildTokenizedLineForRow (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-mate-language-mode.js:402:23)
    at TextMateLanguageMode.tokenizeNextChunk (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-mate-language-mode.js:290:47)
    at _.defer (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-mate-language-mode.js:274:63)
    at ~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/underscore/underscore.js:666:53
```

### Commands

```
     -3:08.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
comment 0.6.1 
copy-path 0.4.2 
cucumber 0.6.0 
cucumber-autocomplete 0.7.2 
cucumber-step 0.2.0 
directory-color 0.3.0 
export-html 3.1.0 
git-plus 7.10.0 
language-ansi-styles 0.0.2 
language-cucumber 0.0.1 
language-groovy 0.7.0 
language-jenkinsfile 0.1.1 
language-terraform 0.8.1 
markdown-preview-plus 2.5.1 
open-bash-git 2.3.3 
platformio-ide-terminal 2.8.0 
print-atom 0.1.1 
print-code 0.7.1 
remote-ftp 2.1.4 
ruby-test 1.0.2 
split-diff 1.5.2 
terraform-fmt 0.3.0 
vim-mode-plus 1.28.0 
```

**Comment by lloiser** [comment]
Fixed with v0.1.0. Pls update.
